engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
    exclude_paths:
    - "browserstack.svg"
    - "node_modules/"
    - "test/"
    - "build/"
  fixme:
    enabled: true
ratings:
  paths:
  - "**.js"
  - "**.jsx"
exclude_paths:
- "build/"
- "node_modules/"
- ".storybook/"
- "test/"