engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
    channel: "eslint-2"
    config:
      config: ".eslintrc"
    exclude_paths:
    - "browserstack.svg"
    - "node_modules/"
    - "test/"
    - "build/"
    ratings:
      paths:
      - "**.js"
      - "**.jsx"
    checks:
      complexity:
        enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.js"
  - "**.jsx"
exclude_paths:
- "build/"
- "node_modules/"
- ".storybook/"
- "test/"